YT: Add isatty attribute existence check
If sys.stderr does not have isatty attribute `AttributeError: '_StreamWrapper' object has no attribute 'isatty'` can occure during yt_client.read_table call
commit_hash:86a72a033006e6e7ed449e3365826ade76c726c6