yt/core/logging: statically disallow structured tags named `message`
`message` is a reserved identifier used by all our log frameworks for the actual
static message, and users should not be able to override it separately (which
might lead to unexpected behaviour).

This introduces a compile-time check for tag keys, which causes a compilation
error if a user tries to use `message`.

There's no clean way to "throw" a good compiler error, so the diagnostic looks
a bit wonky:

```
error: call to consteval function 'NYT::NLogging::NDetail::StructuredLogKey::StructuredLogKey' is not a constant expression
  631 |         YT_SLOG_EVENT(Logger(), ELogLevel::Info, "test_message", ("message", "my message"));
      |                                                                   ^
structured_log-inl.h:23:9: note: subexpression not valid in a constant expression
   23 |         throw "key 'message' is reserved and can not be used";
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

* Changelog entry
  Type: feature
  Component: core/logging

  Statically check for restricted structured log tags.
commit_hash:49854c3432cd81cc2d572828785a3416ab032c0b