YQL-19747: Fix completion sql/suites testing
Commit messages are self-explanatory.

There was 2 types of errors both from the `EvaluateExpression`.

1. Was from `Y_ENSURE` that `EvaluateExpression` return code is `OK` or `Repeat`.

```scala
...
E   Errors:
E   <main>: Error: (yexception) yql/essentials/sql/v1/complete/analysis/yql/yql.cpp:66: Error
...
```

2. Was from `EvaluateExpression` internals.

```scala
...
E   ??+0 (0x7B5EE3E)
E   ??+0 (0x7B57B76)
E   NYql::OptimizeExpr(TIntrusivePtr<NYql::TExprNode, TDefaultIntrusivePtrOps<NYql::TExprNode>> const&, TIntrusivePtr<NYql::TExprNode, TDefaultIntrusivePtrOps<NYql::TExprNode>>&, std::__y1::function<TIntrusivePtr<NYql::TExprNode, TDefaultIntrusivePtrOps<NYql::TExprNode>> (TIntrusivePtr<NYql::TExprNode, TDefaultIntrusivePtrOps<NYql::TExprNode>> const&, NYql::TExprContext&)>, NYql::TExprContext&, NYql::TOptimizeExprSettings const&)+122 (0x7B5793A)
E   NYql::EvaluateExpression(TIntrusivePtr<NYql::TExprNode, TDefaultIntrusivePtrOps<NYql::TExprNode>> const&, TIntrusivePtr<NYql::TExprNode, TDefaultIntrusivePtrOps<NYql::TExprNode>>&, NYql::TTypeAnnotationContext&, NYql::TExprContext&, NKikimr::NMiniKQL::IFunctionRegistry const&, NYql::IGraphTransformer*, std::__y1::function<TAutoPtr<NYql::IGraphTransformer, TDelete> ()>)+3548 (0x7B2F54C)
E   ??+0 (0x74F717C)
E   NSQLComplete::IYqlAnalysis::Analyze(NYql::TAstNode&, NYql::TIssues&) const+143 (0x74F66AF)
...
```

As `EvaluateExpression` is removed, they should be gone now.

Also error logging was improved by the usage of `FormatCurrentException`. Now message looks like
```scala
<main>: Error: Caught:
(yexception) yql/essentials/sql/v1/complete/sql_complete.cpp:65: Test
??+0 (0x72162C6)
__cxa_throw+97 (0x7216211)
NSQLComplete::TSqlCompletionEngine::CompleteAsync(NSQLComplete::TCompletionInput, NSQLComplete::TEnvironment)+2018 (0xAFBD172)
NSQLComplete::CheckComplete(TBasicStringBuf<char, std::__y1::char_traits<char>>, NSQLComplete::TYqlContext)+1255 (0xAF823E7)
??+0 (0xAF8AF30)
??+0 (0xAF833B7)
NSQLComplete::CheckComplete(TBasicStringBuf<char, std::__y1::char_traits<char>>, NYql::TAstNode&, NYql::TIssues&)+96 (0xAF83220)
```

---

- Related to `YQL-19747`
- Related to https://github.com/vityaman/ydb/issues/47
- Related to https://github.com/ytsaurus/ytsaurus/pull/1286

---

Pull Request resolved: https://github.com/ytsaurus/ytsaurus/pull/1322
commit_hash:0840f9a5a8fa78c13fa079d71e63a1934f9d0642