[yt]: Get rid of implicitly declared default copy constructor in order to avoid -Wdeprecated-copy error
https://timsong-cpp.github.io/cppwp/n4659/depr.impldec

```
The implicit definition of a copy constructor as defaulted is deprecated if the class has
a user-declared copy assignment operator or a user-declared destructor. The implicit definition
of a copy assignment operator as defaulted is deprecated if the class has a
user-declared copy constructor or a user-declared destructor (15.4, 15.8).
In a future revision of this International Standard, these implicit definitions could become deleted (11.4).
```

It blocks update of standard library: https://a.yandex-team.ru/review/5084628/details

```
In file included from $(SOURCE_ROOT)/yt/yt/library/numeric/unittests/piecewise_linear_function_ut.cpp:2:
$(SOURCE_ROOT)/yt/yt/library/numeric/piecewise_linear_function.h:385:9: error: definition of implicit copy assignment operator for 'TLeftToRightTraverser' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
        TLeftToRightTraverser(const TLeftToRightTraverser& other) = default;

        ^
$(SOURCE_ROOT)/yt/yt/library/numeric/piecewise_linear_function-inl.h:892:20: note: in instantiation of function template specialization 'std::vector<NYT::TPiecewiseLinearFunction<double>::TLeftToRightTraverser>::emplace_back<NYT::TPiecewiseLinearFunction<double>::TLeftToRightTraverser>' requested here
        traversers.emplace_back(func.GetLeftToRightTraverser());
                   ^
$(SOURCE_ROOT)/yt/yt/library/numeric/unittests/piecewise_linear_function_ut.cpp:489:60: note: in instantiation of member function 'NYT::TPiecewiseLinearFunction<double>::Sum' requested here
        auto sumResult = TPiecewiseLinearFunction<double>::Sum(testCase.Functions);
                                                           ^
1 error generated.
```