Add missing includes when _LIBCPP_REMOVE_TRANSITIVE_INCLUDES enabled
This refactoring belongs to: https://github.com/ClickHouse/ClickHouse/pull/58770

Fixes the following kinds of errors:

```
$(SOURCE_ROOT)/contrib/clickhouse/src/Storages/StorageLogSettings.h:9:29: error: no template named 'shared_ptr' in namespace 'std'
    using ContextPtr = std::shared_ptr<const Context>;
                       ~~~~~^
$(SOURCE_ROOT)/contrib/clickhouse/src/Storages/StorageLogSettings.h:11:50: error: unknown type name 'ContextPtr'; did you mean 'Context'?
    String getDiskName(ASTStorage & storage_def, ContextPtr context);
                                                 ^~~~~~~~~~
                                                 Context
```

**Note: Don't forget to remove this patch when current changes will appear in the upcoming release of ClickHouse.**