Add missing <memory> include for std::make_shared
```
$(SOURCE_ROOT)/yt/cpp/roren/interface/coder.h:217:38: error: 'T' does not refer to a value
            value = std::make_shared<T>();
                                     ^
$(SOURCE_ROOT)/yt/cpp/roren/interface/coder.h:198:20: note: declared here
template <typename T>
                   ^
$(SOURCE_ROOT)/yt/cpp/roren/interface/coder.h:217:21: error: no member named 'make_shared' in namespace 'std'; did you mean 'MakeShared'?
            value = std::make_shared<T>();
                    ^~~~~~~~~~~~~~~~
                    MakeShared
$(SOURCE_ROOT)/util/generic/ptr.h:980:32: note: 'MakeShared' declared here
[[nodiscard]] TSharedPtr<T, C> MakeShared(Args&&... args) {
```