Revert commit cb4daab95981f151c68bca607a0752c92f23b179, Automatic release build for os_test_tool, ya_bin, os_ya, test_tool
Сломали ya package с включенным strip'ом

```
  File "devtools/ya/package/packager.py", line 1458, in build_package
    name, version, path, debug_path = create_package(package_context, output_root, builds)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "devtools/ya/package/utils.py", line 9, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "devtools/ya/package/packager.py", line 754, in create_package
    strip_binaries(params, temp_work_dir, debug_dir, source_elements, full_strip=params.full_strip)
  File "devtools/ya/package/utils.py", line 9, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "devtools/ya/package/packager.py", line 630, in strip_binaries
    file_path = files_to_strip[i][2]
                ~~~~~~~~~~~~~~^^^
TypeError: 'set' object is not subscriptable
```

[Пример](https://nda.ya.ru/t/6akpBI7l7MiMBn
commit_hash:a2a18505064ecd3b1c628a5a157c96af3e84f506