Use proper interface ([] instead of non-existing get()) to get impersonation_user setting from config  [fix:rXXXXXX]
`yt.wrapper list(), get()` and other methods are broken now with

```
  File "yt/python/yt/wrapper/cypress_commands.py", line 401, in list
    result = make_formatted_request(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "yt/python/yt/wrapper/driver.py", line 174, in make_formatted_request
    result = make_request(command_name, params,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yt/python/yt/wrapper/driver.py", line 109, in make_request
    result = http_driver.make_request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-3>", line 2, in make_request
  File "yt/python/yt/wrapper/common.py", line 483, in forbidden_inside_job
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "yt/python/yt/wrapper/http_driver.py", line 287, in make_request
    impersonation_user = get_config(client).get("impersonation_user")
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'yt.wrapper.config' has no attribute 'get'
```

This PR should fix it
commit_hash:c99f2bdff388f7588ef923681ff987ef159d0589