#include <optional> in contrib/ydb/library/actors/interconnect/rdma/rdma.h
Похоже в единицу трансляции с [contrib/ydb/library/actors/interconnect/rdma/rdma.h](https://nda.ya.ru/t/DwazCq6r7N7ue3 не попадает `#include <optional>`, когда как использования `std::optional` в этом файле есть. Похоже я первый, кто компилирует и линкует её после поломки. А именно без этого фикса не собирается инференсер картиночной тушки: `ya make -r -DTENSORFLOW_WITH_CUDA -DCUDA_VERSION=11.8 -DCUDNN_VERSION=8.6.0 -DTENSORRT_VERSION=8 -DOS_SDK=ubuntu-18 extsearch/images/robot/guppy/app`

{% cut "Ошибка" %}

```
------- [CC] {FAILED} $(S)/contrib/ydb/library/actors/interconnect/rdma/rdma.cpp
command (pid: 2218530) /home/sermir2003/.ya/tools/v4/9095799934/bin/python3 /home/sermir2003/arcs/robot/build/scripts/wrapcc.py --source-file /home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/rdma.cpp --source-root /home/sermir2003/arcs/robot --build-root /home/sermir2003/.ya/build/build_root/18lp/000497 --wrapcc-end /home/sermir2003/.ya/tools/v4/10226725676/bin/clang++ --target=x86_64-linux-gnu --sysroot=/home/sermir2003/.ya/tools/v4/617908641 -B/home/sermir2003/.ya/tools/v4/617908641/usr/bin -c -o /home/sermir2003/.ya/build/build_root/18lp/000497/contrib/ydb/library/actors/interconnect/rdma/rdma.cpp.o -I/home/sermir2003/.ya/build/build_root/18lp/000497 -I/home/sermir2003/arcs/robot -I/home/sermir2003/arcs/robot/contrib/libs/linux-headers -I/home/sermir2003/arcs/robot/contrib/libs/linux-headers/_nf -I/home/sermir2003/arcs/robot/contrib/libs/cxxsupp/libcxxcuda11/include -I/home/sermir2003/arcs/robot/contrib/libs/cxxsupp/libcxxrt/include -I/home/sermir2003/arcs/robot/contrib/libs/clang20-rt/include -I/home/sermir2003/arcs/robot/contrib/libs/zlib/include -I/home/sermir2003/arcs/robot/contrib/libs/double-conversion -I/home/sermir2003/arcs/robot/contrib/libs/libc_compat/include/readpassphrase -I/home/sermir2003/arcs/robot/contrib/libs/libc_compat/reallocarray -I/home/sermir2003/arcs/robot/contrib/libs/ibdrv/include -I/home/sermir2003/arcs/robot/contrib/libs/protobuf/src -I/home/sermir2003/arcs/robot/contrib/restricted/abseil-cpp-tstring -I/home/sermir2003/arcs/robot/contrib/restricted/abseil-cpp -fdebug-prefix-map=/home/sermir2003/.ya/build/build_root/18lp/000497=/-B -fdebug-prefix-map=/home/sermir2003/arcs/robot=/-S -fdebug-prefix-map=/home/sermir2003/.ya/tools/v4=/-T -Xclang -fdebug-compilation-dir -Xclang /tmp -pipe -m64 -O3 -g -fdebug-default-version=4 -ggnu-pubnames -fdebug-info-for-profiling -fno-common -ffunction-sections -fdata-sections -fsized-deallocation -fexceptions -fuse-init-array -fcolor-diagnostics -faligned-allocation -Werror -Wall -Wextra -Wno-parentheses -Wno-implicit-const-int-float-conversion -Wno-unknown-warning-option -DARCADIA_ROOT=/home/sermir2003/arcs/robot -DARCADIA_BUILD_ROOT=/home/sermir2003/.ya/build/build_root/18lp/000497 -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_YNDX_LIBUNWIND_ENABLE_EXCEPTION_BACKTRACE -D__LONG_LONG_SUPPORTED -DLIBCXX_BUILDING_LIBCXXRT -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-missing-designated-field-initializers -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-alias-template-in-declaration-name -Wno-cast-function-type-mismatch -Wno-explicit-specialization-storage-class -Wno-extraneous-template-head -Wno-missing-template-arg-list-after-template-kw -Wno-nontrivial-memcall -Wno-strict-primary-template-shadow -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16 -DNDEBUG -Wno-array-parameter -Wno-deprecate-lax-vec-conv-all -Wno-unqualified-std-cast-call -Wno-unused-but-set-parameter -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-function-pointer-types -Wno-address-of-packed-member -Wno-deprecated-this-capture -Wno-missing-designated-field-initializers -Wno-format -Wno-vla-cxx-extension -Wno-invalid-offsetof -Wno-alias-template-in-declaration-name -Wno-cast-function-type-mismatch -Wno-explicit-specialization-storage-class -Wno-extraneous-template-head -Wno-missing-template-arg-list-after-template-kw -Wno-nontrivial-memcall -Wno-strict-primary-template-shadow -std=c++20 -Wimport-preprocessor-directive-pedantic -Woverloaded-virtual -Wno-ambiguous-reversed-operator -Wno-defaulted-function-deleted -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -Wno-deprecated-volatile -Wno-pessimizing-move -Wno-undefined-var-template -nostdinc++ -nostdinc++ -Wno-builtin-macro-redefined -D__DATE__="Jan 10 2019" -D__TIME__="00:00:00" -fmacro-prefix-map=/home/sermir2003/.ya/build/build_root/18lp/000497/= -fmacro-prefix-map=/home/sermir2003/arcs/robot/= -fmacro-prefix-map=/home/sermir2003/.ya/tools/v4/= /home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/rdma.cpp failed with exit code 1 in /home/sermir2003/.ya/build/build_root/18lp/000497
In file included from /home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/rdma.cpp:1:
In file included from /home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/rdma_impl.h:4:
In file included from /home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/events.h:3:
/home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/rdma.h:63:18: error: no template named 'optional' in namespace 'std'
   63 |     virtual std::optional<TErr> DoWrBatchAsync(std::shared_ptr<TQueuePair> qp, std::unique_ptr<IIbVerbsBuilder> builder) noexcept = 0;
      |             ~~~~~^
In file included from /home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/rdma.cpp:1:
/home/sermir2003/arcs/robot/contrib/ydb/library/actors/interconnect/rdma/rdma_impl.h:235:123: error: only virtual member functions can be marked 'override'
  235 |     std::optional<TErr> DoWrBatchAsync(std::shared_ptr<TQueuePair> qp, std::unique_ptr<IIbVerbsBuilder> builder) noexcept override {
      |                                                                                                                           ^~~~~~~~
2 errors generated.
Failed
```

{% endcut %}

Добавление `#include <optional>` сборку [extsearch/images/robot/guppy/app](https://nda.ya.ru/t/D0XOGEpX7N7ue6 фиксит, и я не думаю, что это может что-то сломать.
commit_hash:1429e029cf33ea93883b32547c4c0058339923b6