Support SortColumn in run_sort method
Without this change it is impossible to sort table in descending order without using raw specs:

```python
yt.yson.common.YsonError: Value <yt.wrapper.schema.table_schema.SortColumn object at 0x7f9f258cb450> cannot be serialized to YSON since it has unsupported type "<class 'yt.wrapper.schema.table_schema.SortColumn'>"
```

---
486aab30a10c2faed5a3a37ec2628e1826601d24

Pull Request resolved: https://github.com/ytsaurus/ytsaurus/pull/396