Include yt/yt/library/query/base/parser.h by full path
Short include could sometimes pick "result" file from current directory
instead of generated file from build directory.

In file included from ytsurus/yt/yt/library/query/base/parser.ypp:39:
In file included from ytsurus/yt/yt/library/query/base/lexer.h:4:
build_root/ksqf/001219/yt/yt/library/query/base/parser.h:215:9: error: redefinition of 'TParser'
  class TParser
        ^
build_root/g6w1/00001b/yt/yt/library/query/base/parser.h:215:9: note: previous definition is here
  class TParser
        ^
1 error generated.

---
45acac040346a6261172f305f7718e2b29801186

Pull Request resolved: https://github.com/ytsaurus/ytsaurus/pull/762